from prompts.classify import CLASSIFY_PROMPT
from prompts.coi import COI_EXTRACTION_PROMPT, COI_COMPLIANCE_PROMPT
from prompts.extraction import EXTRACTION_PROMPT
from prompts.lease import LEASE_EXTRACTION_PROMPT, LEASE_ANALYSIS_PROMPT
from prompts.gym import GYM_ANALYSIS_PROMPT
from prompts.employment import EMPLOYMENT_ANALYSIS_PROMPT
from prompts.freelancer import FREELANCER_ANALYSIS_PROMPT
from prompts.influencer import INFLUENCER_ANALYSIS_PROMPT
from prompts.timeshare import TIMESHARE_ANALYSIS_PROMPT
from prompts.insurance_policy import INSURANCE_POLICY_ANALYSIS_PROMPT
from prompts.auto_purchase import AUTO_PURCHASE_ANALYSIS_PROMPT
from prompts.home_improvement import HOME_IMPROVEMENT_ANALYSIS_PROMPT
from prompts.nursing_home import NURSING_HOME_ANALYSIS_PROMPT
from prompts.subscription import SUBSCRIPTION_ANALYSIS_PROMPT
from prompts.debt_settlement import DEBT_SETTLEMENT_ANALYSIS_PROMPT
from prompts.ocr import OCR_PROMPT

__all__ = [
    "CLASSIFY_PROMPT",
    "COI_EXTRACTION_PROMPT",
    "COI_COMPLIANCE_PROMPT",
    "EXTRACTION_PROMPT",
    "LEASE_EXTRACTION_PROMPT",
    "LEASE_ANALYSIS_PROMPT",
    "GYM_ANALYSIS_PROMPT",
    "EMPLOYMENT_ANALYSIS_PROMPT",
    "FREELANCER_ANALYSIS_PROMPT",
    "INFLUENCER_ANALYSIS_PROMPT",
    "TIMESHARE_ANALYSIS_PROMPT",
    "INSURANCE_POLICY_ANALYSIS_PROMPT",
    "AUTO_PURCHASE_ANALYSIS_PROMPT",
    "HOME_IMPROVEMENT_ANALYSIS_PROMPT",
    "NURSING_HOME_ANALYSIS_PROMPT",
    "SUBSCRIPTION_ANALYSIS_PROMPT",
    "DEBT_SETTLEMENT_ANALYSIS_PROMPT",
    "OCR_PROMPT",
]
